//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public Departement()
        {
            this.Employes = new HashSet<Employe>();
        }
    
        public int NumDep { get; set; }
        public string NomDep { get; set; }
        public string Lieu { get; set; }
    
        public virtual ICollection<Employe> Employes { get; set; }
    }
}
