//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.Participations = new HashSet<Participation>();
        }
    
        public int Matr { get; set; }
        public string NomE { get; set; }
        public string Post { get; set; }
        public Nullable<System.DateTime> DateEmb { get; set; }
        public Nullable<int> Sup { get; set; }
        public Nullable<int> Salaire { get; set; }
        public Nullable<int> Comm { get; set; }
        public Nullable<int> NumDep { get; set; }
    
        public virtual Departement Departement { get; set; }
        public virtual ICollection<Participation> Participations { get; set; }
    }
}
