//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participation
    {
        public int Matr { get; set; }
        public int CodeP { get; set; }
        public string Fonction { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
