//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public Projet()
        {
            this.Participations = new HashSet<Participation>();
        }
    
        public int CodeP { get; set; }
        public string NomP { get; set; }
    
        public virtual ICollection<Participation> Participations { get; set; }
    }
}
